add regular systemd notification for watchdog
opencast/pyCA pull request #152
Opened 2018-08-10 21:15 UTC by JanKoppe

This PR adds functionality that will notify a possible systemd instance on control loop iterations, allowing the use of `Type=notify` as described in #144. This should help increase resilience against stuck processes which seems to happen with the ingest worker from time to time.

The used library has no dependencies on systemd, it's essentially a small wrapper around the python socket library. It does not raise any issues if pyCA runs on a system that is using a different init system.

2018-08-15 22:23 UTC, lkiesow requested changes
Can we change `n` to something like `notifier`?

Also, I'm wondering what would happen if you try running this without Systemd? Would the code just run over the notification statements? or would those throw errors?

2018-08-15 22:23 UTC, lkiesow commented on requirements.txt
> +sdnotify>=0.3.2
Can you add this to `setup.py` as well?

2018-08-15 22:23 UTC, lkiesow commented on pyca/schedule.py
> +n = sdnotify.SystemdNotifier()
Can we use something more descriptive than `n`? :-D
What about `notifier`?

2018-08-16 06:55 UTC, JanKoppe commented on requirements.txt
> +sdnotify>=0.3.2
Done!

2018-08-16 06:55 UTC, JanKoppe commented on pyca/schedule.py
> +n = sdnotify.SystemdNotifier()
Done!

2018-08-16 06:56 UTC, JanKoppe commented
> Also, I'm wondering what would happen if you try running this without Systemd? Would the code just run over the notification statements? or would those throw errors?

Yes, it would just go over these statements, i.e. nothing would happen. This is completely compatible with non-systemd distributions.

2018-08-16 12:00 UTC, lkiesow commented
This one has a conflict after merging your other pr

2018-08-16 12:34 UTC, JanKoppe commented
rebased it.

2018-08-16 12:43 UTC, lkiesow approved these changes

2018-08-16 18:38 UTC, merged

2018-08-16 18:59 UTC, lkiesow commented
I've realized that merging this, we need to update all of the installation instructions in the readme file. Since sdnotify is not available on all systems, do you think recommending python virtualenv would make sense?