Update Service Endpoints
opencast/pyCA pull request #200
Opened 2020-06-16 00:57 UTC by lkiesow

This patch ensures that the capture endpoints are updated before
ingesting media to avoid accidentally trying to ingest to a service
which is offline or in maintenance mode.

This fixes #168

---

_This is based on #198 to avoid conflicts._

2020-06-19 09:00 UTC, shaardie commented
I rebased this pull request on the current master

2020-06-19 12:50 UTC, lkiesow commented
Merge conflcts fixed

2020-06-27 10:19 UTC, lkiesow commented
Rebased again.
Fixed merge conflicts again.

2020-07-03 08:36 UTC, shaardie requested changes
Seems to work as expected and, as far as I can tell, it solves #166 and #168 by forcing the list of ingest servers to be updated before every ingest.

Just a minor change and a consideration about the endless retries to get the service.

Another thing I was wondering about is that the `config` seems to be not only used for configuration, but also as some kind of cache object. Since this is done in other places of PyCA too, I consider it being canonical, but I would like to mentioned it here anyway, because it seems kind of weird not to split information cached in memory and configuration loaded from the filesystem.

2020-07-03 08:36 UTC, shaardie commented on pyca/ingest.py
> +    service_url = service('ingest', True)
Maybe be more explicit here, snce it can be missed very easily that this will always update the ingest server and therefore solves #166 and #168

```suggestion
    service_url = service('ingest', force_update=True)
```

2020-07-03 08:36 UTC, shaardie commented on pyca/utils.py
>              time.sleep(5.0)
So, if the request keeps failing, this hangs forever. IMHO this is becoming more important, since the ingest services are now requested every time before the ingest.
The question for me is, is it dangerous to have a service pretending to run, but hanging in the background forever or is this something for the for the watchdog to worry about?

2020-07-03 15:44 UTC, lkiesow commented on pyca/utils.py
>              time.sleep(5.0)
In case of ingest it actually makes sense to wait since you cannot ingest anything unless an ingest endpoints becomes available. Services can disappear in Opencast for various reasons (server shut down, maintenance mode, …). Hence, in this specific use case, it does not only make sense to wait, but it is imperative to wait. Hence, it does not hang, and is not bug. It just waits for Opencast.

But this should be documented. And that's what I did.

2020-07-10 07:15 UTC, merged