Test Parsing Configuration Parameters
opencast/pyCA pull request #202
Opened 2020-06-17 23:55 UTC by lkiesow

This patch adds a unit test for parsing the configuration parameters
passed to pyCA via iCal.

2020-06-19 07:58 UTC, shaardie requested changes
Just a minor suggestion

2020-06-19 07:58 UTC, shaardie commented on tests/test_ingest.py
> +        self.assertEqual(len(parameters), 2)
This is a little bit nicer:

```suggestion
        self.assertEqual([('encode_720p', 'true'), ('cutting', 'false')],
                         parameters)
```

2020-06-19 12:40 UTC, lkiesow commented on tests/test_ingest.py
> +        self.assertEqual(len(parameters), 2)
I think the following result would be valid:

```py
[('cutting', 'false'), ('encode_720p', 'true')]
```

But that's something your test would fail on. We could use sets if you prefer that:

```py
self.assertEqual(set([('encode_720p', 'true'), ('cutting', 'false')]), set(parameters))
```

2020-06-26 07:37 UTC, shaardie commented on tests/test_ingest.py
> +        self.assertEqual(len(parameters), 2)
Yes, you are correct. If the order does not matter, sets would be better.

I personally find the later with the sets more readable than splitting it up in 3 tests, but I am okay with both.

Choose one and feel free to merge then

2020-06-26 07:37 UTC, shaardie approved these changes

2020-06-26 12:54 UTC, lkiesow commented on tests/test_ingest.py
> +        self.assertEqual(len(parameters), 2)
Okay, switched to using sets

2020-06-26 12:57 UTC, merged