Make safe_start_capture actually safe
opencast/pyCA pull request #203
Opened 2020-06-18 00:07 UTC by lkiesow

The method safe_start_capture would still throw an exception if the
agent state could not be set (e.g. due to a network error) which could
cause the capture service to fail.

2020-06-19 08:15 UTC, shaardie requested changes
Although it makes me cringe to see a `try: ... except Exception:` block, this matches the description of this function. But it also says that the exception is logged, so I think the second exception has to be logged then.

Also I am curios. Why is it

```python
try:
    ...
except Exception:
    logger.error(traceback.format_exc())
```

instead of

```python
try:
    ...
except Exception as e:
    logger.exception(e)
```

2020-06-19 08:15 UTC, shaardie commented on pyca/capture.py
> +            logger.error('Could not update recording status')
I think this error should also be logged.

```suggestion
            logger.error('Could not update recording status')
            logger.error(traceback.format_exc())
```

2020-06-19 12:01 UTC, lkiesow commented on pyca/capture.py
> +            logger.error('Could not update recording status')
> Also I am curios. Why is it `logger.error(traceback.format_exc())`

Because either this did not exist back when I wrote this or I did not know better.

Looking at the [logging statement documentation](https://docs.python.org/3/library/logging.html#logging.Logger.debug) it might also make sense to use `exc_info` or `stack_info` within the logger statements

2020-06-26 07:46 UTC, shaardie approved these changes

2020-06-26 07:46 UTC, merged