Logging API Alternative
opencast/pyCA pull request #218
Opened 2020-06-27 09:58 UTC by lkiesow

This patch is a draft for an alternative to storing all logs in the
database (#213). Instead, this patch allows to specify an arbitrary
command responsible for retrieving the logs.

While this gives us less control over the logs (e.g. it is hard to
distinguish different log level), this makes the code much simpler and
removes the burden, the logging puts on the database and the problem
that the database grows indefinitely.

2020-06-27 14:15 UTC, shaardie requested changes
Although I like the approach, since it is much easier to implement and fits to the remaining parts (PyCA also uses such configurable subprocesses for recording and such), I am still a little bit worried, since we are putting all of the work to the administrators. Yes, we are gaining a lot of flexibility out of this, but we also open the door for some mis-configurations. I also thing about those system like Debian where the journal is only accessible with higher privileges. Also some Administrators will potentially have to grep their way through syslog entries or files and could also show kernel logs or audit logs to the ui.

2020-06-27 14:15 UTC, shaardie commented on pyca/ui/jsonapi.py
> +    process = subprocess.Popen(logcmd, stdout=subprocess.PIPE)
Why not using https://docs.python.org/3/library/subprocess.html#subprocess.run?

2020-06-27 14:15 UTC, shaardie commented on pyca/ui/jsonapi.py
> +            'lines': logs}})
Seems like the output does not really fit in the `jsonapi´ data. Maybe better use `meta` like in `pyca.jsonapi.internal_state`.

2020-06-28 22:56 UTC, lkiesow commented on pyca/ui/jsonapi.py
> +    process = subprocess.Popen(logcmd, stdout=subprocess.PIPE)
Nostalgia? :D
What's happening is identical since `run()` just calls `Popen()` and `communicate()` but is probably a bit simpler.
So, yes we could use it.

2020-06-28 23:00 UTC, lkiesow commented on pyca/ui/jsonapi.py
> +            'lines': logs}})
Why would you say that? Can you elaborate?

- `data` is defined as the document’s “primary data” which in case of a log API are clearly the logs, aren't they?
- In contrast to this, `meta` is defined as containing non-standard meta-information. But the log lines are no meta information about the log object.

2020-06-29 07:32 UTC, shaardie commented on pyca/ui/jsonapi.py
> +            'lines': logs}})
I think what bothers me about this is the hard-coded `id` tag, which identifies a resources which is changing over time. So the call is not idempotent.

But I take a second looking at the [specs](https://jsonapi.org/format/#document-resource-object-identification) and this seem to be fine. It only has to identify a *single, unique resource* and I think this is also true for a changing resource.

2020-06-29 07:47 UTC, lkiesow commented on pyca/ui/jsonapi.py
> +            'lines': logs}})
If that's what is bothering you, we can just use a timestamp as id :D

2020-06-29 13:33 UTC, shaardie commented on pyca/ui/jsonapi.py
> +            'lines': logs}})
That would be better ;-)

2020-07-03 09:14 UTC, shaardie requested changes
It works as expected, but after testing this on my own machine (Arch Linux), I realized we potentially create a *very slow* api endpoint with this approach.

Stats from my machine

```bash
# Cold
time journalctl -n 50 -u "pyca*" > /dev/null
journalctl -n 50 -u "pyca*"  0.14s user 0.45s system 9% cpu 6.356 total

# Hot
time journalctl -n 50 -u "pyca*" > /dev/null
journalctl -n 50 -u "pyca*"  0.20s user 0.19s system 100% cpu 0.389 total

# Much faster without glob
ttime journalctl -u "pyca-schedule" -u "pyca-ingest" -u "pyca-capture" -u "pyca-ui" -u "pyca" -u "pyca-agentstate"
journalctl -u "pyca-schedule" -u "pyca-ingest" -u "pyca-capture" -u "pyca-ui"  0.01s user 0.07s system 99% cpu 0.084 total
```

At least we should change the example command to not use `"pyca*"`.

2020-07-03 09:14 UTC, shaardie commented on etc/pyca.conf
> +# Command to execute for gathering logs lines which are then published via the
```suggestion
# Command to execute for gathering logs which are then published via the
```

2020-07-03 16:33 UTC, lkiesow commented
I tend to keep the glob since that's the command that should keep working even if things slightly change like, for example, if new services are added. If we use this specific command, then that can easily break.

The default is also, that no command is defined. That means, that we have no problem with speed. If someone chooses to define a command, optimization can happen right there.

2020-07-10 07:03 UTC, merged

2020-07-10 07:03 UTC, shaardie commented
So even more responsibility for the admin :smile:, but okay. At least we know now how to speed things up.