163 random delay
opencast/pyCA pull request #238
Opened 2020-08-07 13:50 UTC by olabri

for issue #163

2020-08-07 14:43 UTC, lkiesow requested changes
While I haven't actually testing this, this looks good and should work.
A few minimal comments about logging.
And can you make sure to add the new configuration options plus documentation to [etc/pyca.conf](https://github.com/opencast/pyCA/blob/master/etc/pyca.conf)?

2020-08-07 14:43 UTC, lkiesow commented on pyca/ingest.py
> +            logger.info ("delaying %s second" % delay)
```suggestion
            logger.info ("Delaying ingest for %s seconds", delay)
```

Minimal change but improves performance since the logger will only construct the string if necessary instead of them being always constructed. This will not really make a noticeable difference here but it's good to not start with bad habits ;-P

2020-08-07 14:43 UTC, lkiesow commented on pyca/ingest.py
> +            logger.info ("done delaying")
We log starting ingest already, so you will notice that the delay is over anyway
```suggestion
```

2020-08-07 14:46 UTC, lkiesow commented on pyca/ingest.py
> +            delay = random.randint(config()['ingest']['delay_min'],config()['ingest']['delay_max'])
I just realized that you could also use the arguably nicer form of:
```suggestion
            delay = random.randint(config('ingest', 'delay_min'), config('ingest', 'delay_max'))
```

2020-08-07 14:49 UTC, lkiesow requested changes

2020-08-07 14:49 UTC, lkiesow commented on pyca/config.py
> +[ingest]
And [Travis CI complains](https://travis-ci.org/github/opencast/pyCA/builds/715843876) since the section `[ingest]` already exists. You should be able to simply move the new options into the existing section.

2020-08-10 06:40 UTC, olabri commented on pyca/ingest.py
> +            delay = random.randint(config()['ingest']['delay_min'],config()['ingest']['delay_max'])
thank you. changes commited

2020-08-10 06:40 UTC, olabri commented on pyca/config.py
> +[ingest]
thank you. changes commited

2020-08-21 12:36 UTC, lkiesow commented
Hi @olabri, just wondering what the current status for this is. Travis CI is still failing due to the duplicated configuration section in `pyca/config.py`. Do you need any help with that?

2020-09-04 08:06 UTC, olabri commented
sorry Lars for the delay. It's been some crazy weeks here! We are now running 118 rooms on 4 pyca VM's!

2020-10-13 22:46 UTC, lkiesow commented
Now I'm the slow one. Rebased this and fixed the merge conflicts.
Will test it tomorrow and hopefully get it in.

> We are now running 118 rooms on 4 pyca VM's!

If you happen to have time, it would be awesome if you could show off what you are doing in a future adopters meeting.
I't really interested in seeing what infrastructure you built with this

2020-10-13 22:47 UTC, lkiesow approved these changes

2020-10-14 23:15 UTC, merged

2020-10-14 23:15 UTC, lkiesow commented
Tested. Works as expected. Merged.
Thanks for the patch, @olabri