Add Dockerfile
opencast/pyCA pull request #242
Opened 2020-08-20 10:25 UTC by mtneug

This PR improves upon @lkiesow Dockerfile and introduces some more examples with different databases.

Note that I still have the following problems that are likely not related to running pyCA in containers:

1. using PostgreSQL: 
```
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)
```
2. using MariaDB: straight up does not work as the schema cannot be created:
```
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1170, "BLOB/TEXT column 'uid' used in key specification without a key length")
```

SQLite works without problems.

2020-08-20 10:46 UTC, lkiesow commented
The first issue should be solved once https://github.com/opencast/pyCA/pull/232 is merged

2020-09-01 11:36 UTC, mtneug commented
Once elan-ev/static-ffmpeg#24 is merged, I will revert the last commit and use Opencast's ffmpeg. At least ALSA can then be used. Pulseaudio and co. could be added afterwards.

2020-09-29 14:36 UTC, mtneug commented
I changed it back to Opencast's `ffmpeg` version. Is there anything missing?

2020-12-01 21:59 UTC, lkiesow requested changes

2020-12-01 21:59 UTC, lkiesow commented on init/container/pyca.mariadb.conf
> +###
These configuration files are outdated already and are bound to become outdated over and over again. Realistically, you will need to change the configuration anyway. 
That is why I think it makes more sense to remove these and place a short readme here instead.
It would just need to explain that you should copy the configuration file from `../../etc/pyca.conf` to this folder and set (for postgres or mysql):

```
database = mysql://pyca:pyca@database/pyca
database = postgresql://pyca:pyca@database/pyca
```

2020-12-01 21:59 UTC, lkiesow commented on init/container/docker-compose.sqlite.yml
> +      - pyca:/var/lib/pyca
Unfortunately, this does not seem to work.
The volume seems to belong to the user `root`:
```
~ $ ls -ld /var/lib/pyca/
drwxr-xr-x    2 root     root          4096 Dec  1 20:49 /var/lib/pyca/
```

Since pyCA is run as `pyca`, this results in an error:

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
```

2020-12-01 21:59 UTC, lkiesow commented on init/container/docker-compose.mariadb.yml
> +services:
Running this resulted in:
```
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to MySQL server on 'database' (111)")
```

The same goes for the PostgreSQL variant which starts pyCA before starting the database, causing the pyCA container to fail. Q wuick test with `depends_on` with postgres seemed to work but I didn't run a full test. I may make sense to wait on the database to actually be available before starting pyCA.

2020-12-02 10:20 UTC, mtneug commented on init/container/docker-compose.sqlite.yml
> +      - pyca:/var/lib/pyca
This should work at least with Docker. The volume initially inherits the contents from the container if a folder already exists. Maybe this is different for other runtimes e.g. Podman. In production you would need to handle this yourself I would say.

2020-12-02 10:26 UTC, mtneug commented on init/container/docker-compose.mariadb.yml
> +services:
`depends_on` will only start the containers in the specified order, but this says nothing about readiness. The DB container is created beforehand, but if it takes minutes to start, pyCA can still not connect to it.

Starting order can be solved in multiple ways. Most often the easiest and most reliable way is a simple crash loop as implemented here. The pyCA containers will fail and `docker-compose` will start them up again. The system as a whole then converges into a ready state.

2020-12-02 10:26 UTC, mtneug commented on init/container/pyca.mariadb.conf
> +###
I will add a README.

2020-12-02 16:02 UTC, mtneug commented
I just tested MariaDB again and pyCA still seems to have issues with creating the schema.

2021-02-02 08:14 UTC, shaardie commented on init/container/docker-compose.mariadb.yml
> +services:
There are also tools out there handling the wait for you, like https://github.com/ufoscout/docker-compose-wait. Or simply a combination of `until` and `nc`.

2021-02-02 09:14 UTC, mtneug commented on init/container/docker-compose.mariadb.yml
> +services:
@shaardie thanks for the feedback.

As I said, I know those approaches and have used them in the past (e.g. the Opencast images currently wait for the DB to go up). Maybe not in the case of pyCA, but the coordination logic for the proper startup order of larger systems can be quite complex (is the DB actually ready or is just the port open? is every subsystem initialized? etc.). It is therefore often recommended to just fail and let the orchestrator start the service again (crash loop). The startup time of pyCA is very quick and this approach therefore very cheap.

2021-02-09 14:59 UTC, lkiesow commented
> I just tested MariaDB again and pyCA still seems to have issues with creating the schema.

That's correct. Starting the container will fail with:

```sql
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1170, "BLOB/TEXT column 'uid' used in key specification without a key length")
[SQL: 
CREATE TABLE upcoming_event (
        uid TEXT NOT NULL, 
        start INTEGER NOT NULL, 
        end INTEGER NOT NULL, 
        title TEXT, 
        data BLOB NOT NULL, 
        `status` INTEGER NOT NULL, 
        tracks BLOB, 
        PRIMARY KEY (uid, start)
)
```
Since that's the case, I suppose it does not make sense to promote MariaDB in here unless the problem gets resolved first.
Do you want to address that problem?
Otherwise, my suggestion would be to drop MariaDB and merge the other ones.
I went through the other cases and they seem to work well.

---

Finally, it would make sense to have some documentation on https://github.com/opencast/pyCA/tree/master/docs/install
But I can see that it might make sense to wait for Quay.io to be hooked up first?

2021-02-10 15:43 UTC, mtneug commented
I removed the MySQL parts.

As for the documentation: this PR only contains a minimal README in `init/container`. My question is, what use case should be documented? I don't see `docker-compose` as a deployment tool but rather for local testing. We use pyCA container images on some capture agents running a one node Kubernetes cluster using the k3OS Linux distribution. This is probably a very unusual scenario, but I could supply some Kubernetes manifests that showcase an ALSA and Video4Linux scenario. Or do you think a simple FFmpeg test image is sufficient? In the Kubernetes case, a better approach would be to setup a Helm repository (Helm is a "package manager" for Kubernetes) that hosts those manifests and maybe additional ones in the future (e.g. Opencast).

Not directly related to pyCA, but the ALSA case might be worth documenting: If more than one container/Pod needs to access the same audio device both containers/Pods need to be in the same IPC namespace (e.g. if you have a separate container for livestreaming). Currently, we simply use the host IPC namespace (`hostIPC: true` in Pod manifest).

Regardless, should I file another PR or do you want me to add to this one?

2021-02-10 19:44 UTC, merged

2021-02-10 19:54 UTC, lkiesow commented
I agree that your usage is special and I would guess that most people would use containerized versions more for things like capturing network camera streams.

But for the documentation I was more thinking about that right now, you have to intentionally look for the docker-compose files. If you look at the [documentation](https://github.com/opencast/pyCA/tree/master/docs#installation), there is no mention of the existence of containers. Thus, I think that a simple entry  telling people that the option exists would already be very helpful. What people built based on that is then up to them.

In any case. This pull request is merged and I can provide a short documentation entry once quay.io is hooked up to this repository.