Patch for issue 30: Adds a re-ingest button in the recording table
opencast/pyCA pull request #251
Opened 2020-08-24 11:13 UTC by mheyen

This patch adds a re-ingest button in the recording table if the recording is in state FAILED_UPLOADING

clicking the button will change the status of the recording to FINISHED_UPLOADING by sending a request to the pyCA API.
It will modify the state of the recording via PATCH /api/events/<uid> and pyCA will automaitcally try to re-upload the recording.

this fixes #30

2020-08-24 12:17 UTC, lkiesow requested changes

2020-08-24 12:17 UTC, lkiesow commented on ui/func.js
> +                        })
`update_data` is already a function:
```suggestion
                        fetch("/api/events/" + event.id, requestOptions).then(update_data);
```

2020-08-24 12:17 UTC, lkiesow commented on ui/func.js
> +                            </button>
The button does not really fit with the rest of the user interface layout and causes an additional visual issue when hovering over it:

![ui-before](https://user-images.githubusercontent.com/1008395/91043273-9a8e3700-e613-11ea-8ac7-19939ab29021.gif)

Why not just stick to the icons?

![ui-after](https://user-images.githubusercontent.com/1008395/91043337-b396e800-e613-11ea-850f-6e3a7c98b3c8.gif)

My suggestion would be to do something like

```diff
diff --git a/ui/func.js b/ui/func.js
index d7dd012..2835f8a 100644
--- a/ui/func.js
+++ b/ui/func.js
@@ -185,13 +185,14 @@ window.onload = function () {
                     <td>
                         <div class=event_status>
                             {{ event.status }}
-                            <span v-if="is_error_state(event)">
+                            <span class=warning v-if="is_error_state(event)">
                             <font-awesome-icon icon="exclamation-triangle" />
                             </span>
-                            <span v-if="event.status == 'failed uploading'">
-                            <button type="button" class="more" v-on:click="retry_ingest(event)">
-                                <font-awesome-icon icon="sync" /> retry
-                            </button>
+                            <span class=action
+                                  v-if="event.status == 'failed uploading'"
+                                  v-on:click="retry_ingest(event)"
+                                  title="Retry upload">
+                                <font-awesome-icon icon="sync" />
                             </span>
                         </div>
                     </td>
diff --git a/ui/style.css b/ui/style.css
index 6245ebc..66cb8df 100644
--- a/ui/style.css
+++ b/ui/style.css
@@ -131,10 +131,14 @@ div.event_status {
     justify-content: space-between;
 }
 
-div.event_status span {
+div.event_status span.warning {
     color: red;
 }
 
+div.event_status span.action {
+    cursor: pointer;
+}
+
 div.logs {
     width: 100%;
     overflow-x: scroll;

```

2020-08-24 12:17 UTC, lkiesow commented on ui/func.js
> +                    retry_ingest: event => {
The visual feedback for this action might take some time. This might cause users to click retry multiple times, causing multiple updates. We should deactivate, [deactivate and animate](https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons) or remove the icon once it has been clicked.

2020-08-24 15:17 UTC, mheyen commented on ui/func.js
> +                    retry_ingest: event => {
I actually looked at the spinner animation before and tried to include it. I can simply add the fa-spin class. 
But how do I deactivate the retry_ingest function, once it has been triggered?

2020-08-26 13:13 UTC, mheyen commented on ui/func.js
> +                    retry_ingest: event => {
The animation should be working now. Within the `retry_ingest` function the event is set to being processed and the spin animation is bound to the processed variable. Thus, the animation should last until the events are updated again with the new modified status. 
However, I am not sure about the error handling in case the backend pyCA API is returning an error code. Do you have a suggestion how to properly implement that?

2020-08-26 21:39 UTC, lkiesow commented on ui/func.js
> +                    retry_ingest: event => {
One thing that still remains is the problem that the state resets if the events reload e.g. because `update_data` just got called which happens every few seconds. This only becomes a problem if you use a non-single threaded web server (the dev server is single threaded) like gunicorn:

```
% gunicorn --config=etc/gunicorn.conf.py --log-level=debug pyca.ui:app

```

For the following test I used gunicorn as web server, set `?refresh=2` and deliberately slowed down the patch request making sure that the problem is visible:

![pyca-retry-button-reappears](https://user-images.githubusercontent.com/1008395/91358548-5063ac00-e7f3-11ea-8eee-ba7aa91ec72a.gif)

Here you see that I click the icon, it starts spinning, then `update_data` is called, resetting the state until a few seconds later the backend is finished and `update_data` is called yet again.

To fix this you could add a global array of processing events, then do something like

```js
var create_event = function() {
  …
  'processing': processing_events.indexOf(id) >= 0,
```
…and then in `retry_ingest` so something like:

```
processing_events.push(event.id)
fetch(…)
.finally(() => {
  processing_events.pop(event.id);
  update_data();
})
```

---

Error handling is indeed somewhat tricky. Mainly because there is no real place where we could display errors right now. Displaying it at the top of the page may be hidden to users taking action further down the page. We could add a red sticky notification bar at the top. But let's leave that for another pull request and keep the error in the logs for now.

2020-08-31 18:33 UTC, merged