Added upload rate limitation option
opencast/pyCA pull request #270
Opened 2020-10-08 10:48 UTC by wsmirnow

In some cases you want to limit the upload rate. This may be the case on less powerfull machines like raspberry pi SoCs.

2020-10-08 11:55 UTC, lkiesow requested changes
Generally looks good. Two suggestions.

2020-10-08 11:55 UTC, lkiesow commented on pyca/utils.py
> +                upload_rate)
Instead of checking this every time we do a request, it makes more sense to check this immediately when the configuration is loaded. There is a `check()` method for this already:

https://github.com/opencast/pyCA/blob/15288d934b9258d18ed2bb018798759e52e1d0b7/pyca/config.py#L111-L112

In there, I also wouldn't catch the `ValueError`. That will cause an error immediately when you misconfigure something and you have to fix it instead of defaulting to something you likely did not want/expect since you didn't notice that there was a configuration error.

The part here in `http_request(…)` would then simply become something like (assuming 0 means no limit):

```suggestion
    if config('ingest', 'limit_upload_rate'):
        config.setopt(curl.CURLOPT_MAX_SEND_SPEED_LRGE, config('ingest', 'limit_upload_rate'))
```

The check/conversion in `check()` could be something like:

```
    if config('ingest', 'limit_upload_rate'):
        # Limit upload rate in bytes per second
        upload_rate = config('ingest', 'limit_upload_rate').lower()
        if upload_rate.endswith('m'):
            upload_rate = upload_rate[0:-1] + '000000'
        elif upload_rate.endswith('k'):
            upload_rate = upload_rate[0:-1] + '000'
        config('ingest')['limit_upload_rate'] = int(upload_rate)
```
Of course, the default would then need to be `0`

2020-10-08 11:55 UTC, lkiesow commented on pyca/config.py
> +limit_upload_rate   = string(default='')
I'm wondering if `ingest.upload_rate` would be cleaner. The `limit_upload_rate` kind of sounds like a question (boolean). From the names, I would basically expect:

```
limit_upload_rate = True
```
but
```
upload_rate   = 10m
```
What do you think?

2020-11-02 19:08 UTC, wsmirnow commented on pyca/utils.py
> +                upload_rate)
Agree

2020-11-02 19:09 UTC, wsmirnow commented on pyca/config.py
> +limit_upload_rate   = string(default='')
Agree, too.

2020-11-02 20:16 UTC, wsmirnow commented
Fixed merge conflict, implemented suggestions and rebased. Please, go ahead.

2020-12-01 19:25 UTC, merged