This patch implements upload-button in backupmode.
opencast/pyCA pull request #295
Opened 2021-01-05 12:42 UTC by CGreweling

It is possible to ingest the recorded file into an existing mediapackage.
In Backup-mode the ca records simultaneously to the ca with the same name.
But it will not ingest the recording automatically.
The ingest can be triggered with the ui through clicking on a button.

2021-01-28 10:04 UTC, CGreweling commented
@lkiesow have not recognized the conflicts here as i opened the pr. 
Solved them now. 
The 3.8 tests failed ``` Unprocessable Entity for url: https://coveralls.io/api/v1/jobs ```. I do not know what that means.

2021-02-09 13:53 UTC, lkiesow commented
Rebased to fix build issue with coveralls

2021-02-09 23:59 UTC, lkiesow requested changes
Generally looks good. I found one small error and have one suggestion for slightly different naming.

2021-02-09 23:59 UTC, lkiesow commented on pyca/capture.py
> +    if config('agent')['backup_mode']:
You always overwrite the status `PARTIAL_RECORDING`. If it's set. it should stay:

```suggestion
    elif config('agent', 'backup_mode'):
```

2021-02-09 23:59 UTC, lkiesow commented on pyca/db.py
> +    FINISHED_RECORDING_PAUSED = 9
The status `finished recording paused` is somewhat confusing for users if you don't already know what it means. How can you pause a recording if it is already finished? What about using:

```suggestion
    PAUSED_AFTER_RECORDING = 9
```

2021-02-10 07:48 UTC, CGreweling commented on pyca/capture.py
> +    if config('agent')['backup_mode']:
Ah okay, i just copied that line from the old code, so the old code did not work anyway.^^

2021-02-10 07:50 UTC, CGreweling commented on pyca/db.py
> +    FINISHED_RECORDING_PAUSED = 9
I am fine with it, by the way that was your suggestion a while ago. ;)
But then this must also be changed i the ``` Event.vue ```

2021-02-10 11:14 UTC, lkiesow approved these changes

2021-02-10 11:19 UTC, merged