implemented prometheus-metrics as flask middleware at /metrics
opencast/pyCA pull request #336
Opened 2021-08-05 09:34 UTC by tobischenk

This Pull request is thought to add prometheus metrics to pyca. The metrics are retrievable at '/metrics'. The metrics include prometheus-client default metrics and two custom collectors to return metrics about the status of pyca services and info about upcoming and recorded events.

Changes:
- setup.py, requirements.txt: Added prometheus-client library
- pyca/ui/__init__.py: changed to include prometheus metrics as flask middleware at endpoint /metrics
- pyca/ui/process_status_collector.py: Custom Collector for pyca service status
- pyca/ui/recordings_collector.py: Custom Collector for recorded and upcoming events

2021-08-06 18:12 UTC, lkiesow requested changes
Hi @tobischenk,
thanks for the patch.

As you have probably seen, the tests fail on this pull request. The CodeQL seems to have started complaining about old code. Feel free to ignore that. The other tests should succees though. Can you fix your code accordingly?

I've also added some comments related to the code itself.
Let me know if you think any of the comments make no sense.

Finally, it would be great to add tests for the new code.

2021-08-06 18:12 UTC, lkiesow commented on pyca/ui/recordings_collector.py
> +        # Filter RecordedEvents for different Status
We can make the whole block simpler and have it automatically adjust if new status are ever introduced, by doing something like this:

```diff
diff --git a/pyca/db.py b/pyca/db.py
index c15191d..85e0aad 100644
--- a/pyca/db.py
+++ b/pyca/db.py
@@ -71,6 +71,13 @@ class Constants():
             if k[0] in string.ascii_uppercase and v == value:
                 return k.lower().replace('_', ' ')
 
+    @classmethod
+    def values(cls):
+        for key, value in vars(Status).items():
+            if not key.startswith('_'):
+                yield value
+
 
 class Status(Constants):
     '''Event status definitions
diff --git a/pyca/ui/recordings_collector.py b/pyca/ui/recordings_collector.py
index 386f426..ebf2b6b 100644
--- a/pyca/ui/recordings_collector.py
+++ b/pyca/ui/recordings_collector.py
@@ -15,54 +15,27 @@ class RecordingsCollector(object):
         '''
         Return metrics about upcoming and recorded Events
         '''
-        recordings = GaugeMetricFamily('pyca_events_count',
-                                       'Count of Recorded Events with different status',
-                                       labels=['type'])
-        recordings.add_metric(
-            ['upcoming'],
-            value=self.db.query(UpcomingEvent).filter(UpcomingEvent.start >= timestamp()).count()
-        )
-        recordings.add_metric(
-            ['recording'],
-            value=self.db.query(RecordedEvent).filter(RecordedEvent.status == Status.RECORDING).count()
-        )
+        recordings = GaugeMetricFamily(
+                'pyca_events_count',
+                'Count of recorded events with different status',
+                labels=['type'])
 
         recorded_events = self.db.query(RecordedEvent)
 
         # Filter RecordedEvents for different Status
-        recordings.add_metric(
-            ['failed_recording'],
-            value=recorded_events.filter(RecordedEvent.status == Status.FAILED_RECORDING).count()
-        )
-
-        recordings.add_metric(
-            ['finished_recording'],
-            value=recorded_events.filter(RecordedEvent.status == Status.FINISHED_RECORDING).count()
-        )
+        for status in Status.values():
+            recordings.add_metric(
+                [Status.str(status)],
+                value=recorded_events.filter(RecordedEvent.status == status)
+                                     .count()
+            )
 
+        # Overwrite number of upcoming events
         recordings.add_metric(
-            ['uploading'],
-            value=recorded_events.filter(RecordedEvent.status == Status.UPLOADING).count()
-        )
-
-        recordings.add_metric(
-            ['failed_uploading'],
-            value=recorded_events.filter(RecordedEvent.status == Status.FAILED_UPLOADING).count()
-        )
-
-        recordings.add_metric(
-            ['finished_uploading'],
-            value=recorded_events.filter(RecordedEvent.status == Status.FINISHED_UPLOADING).count()
-        )
-
-        recordings.add_metric(
-            ['partial_recording'],
-            value=recorded_events.filter(RecordedEvent.status == Status.PARTIAL_RECORDING).count()
-        )
-
-        recordings.add_metric(
-            ['paused_after_recordings'],
-            value=recorded_events.filter(RecordedEvent.status == Status.PAUSED_AFTER_RECORDING).count()
+            ['upcoming'],
+            value=self.db.query(UpcomingEvent)
+                         .filter(UpcomingEvent.start >= timestamp())
+                         .count()
         )
 
         yield recordings
```

2021-08-06 18:12 UTC, lkiesow commented on pyca/ui/recordings_collector.py
> +            value=self.db.query(UpcomingEvent).filter(UpcomingEvent.start >= timestamp()).count()
This isn't actually correct upcoming recordings can have start times after the current time w.g. if pyCA was started late, the event was added last minute to Opencast or there is a network issue preventing updating the schedule in time.

The accurate number would be the set of events in `UpcomingEvent` minus the set of events in `RecordedEvent`. You can be smarter by just excluding the event currently being recorded.

2021-08-06 18:12 UTC, lkiesow commented on pyca/ui/process_status_collector.py
> +        }
Converting this to strings in between is unnecessary and with the change proposed for recordings, you can just do:

```suggestion
        return { ServiceStatus.str(s):s == state for s in ServiceStatus.values() }
```
and then something like:

```py
self.get_state_dict(get_service_status(Service.AGENTSTATE))
```

2021-08-06 18:12 UTC, lkiesow commented on pyca/ui/process_status_collector.py
> +        )
You can do somthing like:

```suggestion
        for service in Service.values():
            service_states.add_metric(
                [Service.str(service)],
                self.get_state_dict(get_service_status(service))
            )
```

2021-08-06 18:20 UTC, lkiesow commented
CodeQL check is fixed.

2021-08-09 12:09 UTC, tobischenk commented
I fixed the linting errors regarding unused import statements in https://github.com/opencast/pyCA/pull/336/commits/a28bdb4d1572faea21e929d007e7b53774b063c3

In https://github.com/opencast/pyCA/pull/336/commits/9d7f4269ec72ce6925e189792e3891f81be1b677 i added the values method to pyca/db.py Constant in order to use it in the custom collectors.

I adjusted the custom collectors in https://github.com/opencast/pyCA/pull/336/commits/6527e5c48df07be488b979f3b027b65b5b18aa55 and fixed linting errors for too long lines, but I am unsure if understood the calculation in  https://github.com/opencast/pyCA/pull/336#discussion_r684403415 correctly.

2021-08-09 14:50 UTC, lkiesow commented
> but I am unsure if understood the calculation in #336 (comment) correctly.

You mean the calculation of upcoming events?

2021-08-09 15:18 UTC, tobischenk commented
> > but I am unsure if understood the calculation in #336 (comment) correctly.
> 
> You mean the calculation of upcoming events?

Yes exactly. I am not sure if the implementation in https://github.com/tobischenk/pyCA/blob/6527e5c48df07be488b979f3b027b65b5b18aa55/pyca/ui/recordings_collector.py#L32-L41 returns the correct count.

Moreover I removed unused dependencies, which caused the test to fail in ce961c370026fc2777aeaa642a2b626f32c78d72.

Maybe you can run the test again so i can check is something is still failing?

2021-08-10 07:28 UTC, tobischenk commented
Since the test for the Code passed, I will try to add tests in the following week. I will commit the changes and write a new comment once its done.

2021-08-10 23:08 UTC, lkiesow commented
I'll also try to write up a few details about the upcoming events table. Ping me if I forget :-)

2021-08-16 09:14 UTC, lkiesow commented
Here comes a short explanation of how the two recording tables work and why there are two in the first place.
Let's start with what the tables are doing:

- `upcoming_event` acts like a cache for whatever events Opencast lists for pyCA. It is more or less a semi-persistent representation of Opencast's iCal feed for the capture agent. The table will be truncated and refilled with each successful update.
- `recorded_event` holds the events pyCA has accepted and started to process. It is also used to keep track of the recording's state. pyCA may modify events in here, store additional data, …

So, `recorded_event` is more or less a classic database table, and you can interact with it the way you would expect. The `upcoming_event` may be a bit more confusing, however.

First, this table exists just as a cache. The reason for this is that we want to compensate for common infrastructure failures as good as we can. These include network failures or power failures. The way it is build, pyCA can loose network and power but as soon as it starts up again, it can work independently and capture events to the best of his knowledge, even if the network doesn't come up again. This is something I've actually seen in real life. Networks aren't always as resilient as one would think and if there is a larger problem, one lecture hall's network may also not be the top priority.

This means whatever Opencast sends us is in `recorded_event` and that's all upcoming recordings, including those which should already have started. The reasoning for Opencast including those is similar: If a capture agent connects late or gets the update late, it is better to start a bit late, than to not start at all.

What now happens is that pyCA picks a recording, starts processing and copies the recording to `recorded_event`. But the same recording is still in `upcoming_event`. Even if we would remove the event from that table when we start the next recording, it would be back again with the next update we get from Opencast. Besides, we use this for trying to restart events which capture command failed at some point.

What this boils down to is that there may be events in `upcoming_event` which are also already tracked in `recorded_event`. To count the events which aren't in another state and are indeed still upcoming, we would thus need to count the events which are not present in `recorded_event` (e.g. check for each event if it is in that table and exclude the event if it is). But we can make this a bit easier by using some internal knowledge: In production, only the newest event in `recorded_event` should potentially be present in `upcoming_event`. So, you could do something like (pseudo code):

```
latest_recorded_id = select id from recorded_event order by date desc limit 0, 1;
upcoming = select count(*) from upcoming_event where id != latest_recorded_id;
```

Now, if you are strict about it, you could potentially construct cases where this is not true by deleting and thus creating some overlapping last minute events in Opencast but given that this is about metrics, I think we can safely ignore that.

2021-08-16 09:18 UTC, lkiesow commented
…actually, thinking about this for a moment, I think we can even get the edge cases relatively easy without comparing everything by doing something like:

```
# Get list of events which are potentially still in upcoming
recorded_ids = select uid from recorded_event where end > timestamp();
# Count all events which aren't already in recorded_event
upcoming = select count(*) from upcoming_event where not uid in recorded_ids;
```

2021-08-18 19:35 UTC, tobischenk commented
Hello Ikiesow,
I changed the calculation of upcoming events. Moreover I tried to write unit test, but I am unsure if they cover all the lines, since its the first time im writing unit tests.

If anything is not according to standards and can be improved, please let me know.

Thanks in advance.

2021-08-30 19:25 UTC, tobischenk commented
@lkiesow can you run the tests again?

Regards tobischenk

2021-10-01 14:00 UTC, lkiesow commented
Sorry for the late reply. Didn't manage to get this merged before my vacation after all.
This looks good → merging.
This also means that all tests will now run automatically for you on new pull requests ;-)

Thanks again for the patch.
I think it is quite useful.

2021-10-01 14:04 UTC, merged