Split pyCA functionality into multiple processes
opencast/pyCA pull request #37
Opened 2016-10-12 16:46 UTC by lkiesow

This is not yet final but only a preview of how the spli-up will look like. Note that this is based on the database pull request #35

2017-02-03 15:40 UTC, lkiesow commented
@JanKoppe, this branch should now be ready to be merged. It should cover all of the previous functionality and already splits up the scheduler and capturer quite nicely. Still, this needs some testing. As you see, there are a lot of changes and even with the automatic tests, we should to some actual recordings.

What is left to do (and I would work on that next) is to split up the ingest part as well. That way it would also be easy to use that for manual or automatic re-ingests in the case of network issues, …

Finally, the user interface needs some additional work. The good thing is that it is already split-up. Still, it needs some work (e.g. proper WSGI integration, list recordings, show current status, …)

Let me know if you find any problems with this.

2017-02-09 11:41 UTC, JanKoppe requested changes

2017-02-09 11:41 UTC, JanKoppe commented on pyca/__main__.py
> +    :copyright: 2014-2016, Lars Kiesow <lkiesow@uos.de>
it's 2017 already! time flies. :)

2017-02-09 11:41 UTC, JanKoppe commented on pyca/db.py
> +class UpcommingEvent(Base, BaseEvent):
"upcoming" is spelled with only one "m". Needs to be changed in a lot of places.

2017-02-09 14:20 UTC, JanKoppe approved these changes

2017-02-09 14:20 UTC, merged